#pragma once



enum {

	LOBBY_WIDGET_ID = WM_USER + 2050,

	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	//BACKGROUND
	/////////////////////////////////////////////////////////////////////////////////////////////////////////

	LOBBY_WIDGET_ID_BG,
	LOBBY_WIDGET_ID_PCPROMOTOPVIEW,		//PC방 상생 프로모션

	LBG_BUTTON_ID_CAPTURE,	
	LBG_BUTTON_ID_OPTION,
	LBG_BUTTON_ID_GAMEMANUAL,
	LBG_BUTTON_ID_GRADE,
	LBG_BUTTON_ID_MINIMIZE,
	LBG_BUTTON_ID_CHANGESCREEN,
	LBG_BUTTON_ID_EXIT,
	LBG_BUTTON_ID_DIRECTBUYITEM,	
	LBG_BUTTON_ID_PCROOM,
	LBG_BUTTON_ID_JACKPOT,
	LBG_BUTTON_ID_VIPCOUNSEL,
	LBG_COMBO_ID_TEST,
	LBG_BUTTON_ID_TIMENOTIFIER,


	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	//SHOP TAB
	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	LOBBY_WIDGET_ID_SHOPTAB,
	LOBBY_WIDGET_ID_SHOPTAB_STATE,

	//view	
	LOBBY_WIDGET_ID_SHOPVIEW_VIEW_SHOP,
	LOBBY_WIDGET_ID_SHOPVIEW_VIEW_EVENT,

	//BUTTONS	
	LGT_BUTTON_ID_SHOPTAB_SHOP, 
	LGT_BUTTON_ID_SHOPTAB_EVENT,


	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	//USER TAB
	/////////////////////////////////////////////////////////////////////////////////////////////////////////


	LOBBY_WIDGET_ID_USER_TAB,

	//LOBBYGAME STATE
	LOBBY_WIDGET_ID_USER_STATE,

	LOBBY_WIDGET_ID_USERTAB_VIEW,
	LOBBY_WIDGET_ID_USERTAB_USERVIEW, 
	LOBBY_WIDGET_ID_USERTAB_FRIENDVIEW, 


	LOBBY_WIDGET_ID_USERLIST,				//유저 리스트 
	LOBBY_WIDGET_ID_USERLIST_UPBUTTON,		//유저 리스트 (업버튼)
	LOBBY_WIDGET_ID_USERLIST_DOWNBUTTON,	//유저 리스트 (다운버튼)
	LOBBY_WIDGET_ID_USERLIST_THUMBBUTTON,	//유저 리스트 (썸버튼)

	LOBBY_BUTTON_ID_USERLIST_SORT_NICKNAME,	//
	LOBBY_BUTTON_ID_USERLIST_SORT_MONEY,
	LOBBY_BUTTON_ID_USERLIST_SORT_POSITION,

	LRO_WIDGET_ID_USERLIST_UNIT, 
	LRO_WIDGET_ID_USERLIST_UNIT_RESERVE= LRO_WIDGET_ID_USERLIST_UNIT+100,


	//BUTTONS
	LUV_BUTTON_ID_USERTAB,
	LUV_BUTTON_ID_USERTAB_USER, 
	LUV_BUTTON_ID_USERTAB_FRIEND,

	LUV_BUTTON_ID_USERTAB_SEARCH_USER,
	LUV_BUTTON_ID_USERTAB_SEARCH_ROOM,
	//EDIT 
	LUV_EDIT_SEARCH_USER,
	LUV_EDIT_SEARCH_ROOM,

	//COMMBO BOX
	LUV_COMBO_GAME,
	LUV_COMBO_MONEY,



	
	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	//GAME TAB
	/////////////////////////////////////////////////////////////////////////////////////////////////////////

	LOBBY_WIDGET_ID_GAMETAB,

	//LOBBYGAME STATE
	LOBBY_WIDGET_ID_LOBBYGAMESTATE,

	//LOBBYGAME
	LOBBY_WIDGET_ID_GAMETAB_BASE, 
	LOBBY_WIDGET_ID_GAMETAB_7POKER,
	LOBBY_WIDGET_ID_GAMETAB_LOWBD,
	LOBBY_WIDGET_ID_GAMETAB_NEWPOKER,
	LOBBY_WIDGET_ID_GAMETAB_HIGHLOW,
	LOBBY_WIDGET_ID_GAMETAB_HOOLA,
	LOBBY_WIDGET_ID_GAMETAB_SUTDA,
	LOBBY_WIDGET_ID_GAMETAB_RESERVE,	

	//BUTTONS
	LGT_BUTTON_ID_GAMETAB,
	LGT_BUTTON_ID_GAMETAB_7POKER, 
	LGT_BUTTON_ID_GAMETAB_LOWBD,
	LGT_BUTTON_ID_GAMETAB_NEWPOKER,
	LGT_BUTTON_ID_GAMETAB_HIGHLOW,
	LGT_BUTTON_ID_GAMETAB_HOOLA,
	LGT_BUTTON_ID_GAMETAB_SUTDA,
	LGT_BUTTON_ID_GAMETAB_RESERVE1,	
	LGT_BUTTON_ID_GAMETAB_RESERVE2,	

	//바로시작 버튼
	LGT_BUTTON_ID_AUTOENTERROOM,
	LGT_BUTTON_ID_AUTOENTERROOM_RESERVE= LGT_BUTTON_ID_AUTOENTERROOM+MAX_GAME,

	//바로시작 버튼
	LGT_BUTTON_ID_AUTOENTERROOM_HA_JOKER,
	LGT_BUTTON_ID_AUTOENTERROOM_HA_NORMAL,

	//내맘대로바로시작 버튼
	LGT_BUTTON_ID_PREMQUICKJOIN,
	LGT_BUTTON_ID_PREMQUICKJOINRESERVE= LGT_BUTTON_ID_PREMQUICKJOIN+MAX_GAME,

	//선택 시작 버튼
	LGT_BUTTON_ID_SELECTSTART,

	//내맘대로바로시작 설정 버튼
	LGT_BUTTON_ID_PREMQUICKJOIN_CONFIG,
	LGT_BUTTON_ID_PREMQUICKJOIN_CONFIG_RESERVE= LGT_BUTTON_ID_PREMQUICKJOIN_CONFIG+MAX_GAME,
	
	//COMMON BUTTONS
	LGT_BUTTON_ID_CREATEROOM,
	LGT_BUTTON_ID_SHOP,
	LGT_BUTTON_ID_EVENT,
	LGT_BUTTON_ID_BUYCHANCEITEM,
	LGT_BUTTON_ID_DEFAULT_SORT,
	


	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	//ROOM TAB
	/////////////////////////////////////////////////////////////////////////////////////////////////////////

// 	LOBBY_WIDGET_ID_ROOM_TAB,
 	LOBBY_WIDGET_ID_ROOM_TAB_STATE,


	LOBBY_BUTTON_ID_ROOMLIST_TAB_VIP,		//VIP게임방 탭버튼
	LOBBY_BUTTON_ID_ROOMLIST_TAB_NORMAL,	//일반게임방 탭버튼
	LOBBY_BUTTON_ID_ROOMLIST_TAB_FREE,		//자유게임방 탭버튼

	//VIP ROOM LIST
	LOBBY_WIDGET_ID_ROOMLIST_VIP,				//방 리스트 
	LOBBY_WIDGET_ID_ROOMLIST_NORMAL,			//방 리스트 
	LOBBY_WIDGET_ID_ROOMLIST_FREE,				//방 리스트 

	


	//방리스트 스크롤 버튼	
	LOBBY_BUTTON_ID_ROOMLIST_UPBUTTON,		//방 리스트 (업버튼)
	LOBBY_BUTTON_ID_ROOMLIST_DOWNBUTTON,	//방 리스트 (다운버튼)
	LOBBY_BUTTON_ID_ROOMLIST_THUMBBUTTON,	//방 리스트 (썸버튼)

	
	//일반 소팅버튼
	LOBBY_BUTTON_ID_ROOMLIST_SORT_ROOM_NO,
	LOBBY_BUTTON_ID_ROOMLIST_SORT_LIMIT,
	LOBBY_BUTTON_ID_ROOMLIST_SORT_SEED_BETRULE,
	LOBBY_BUTTON_ID_ROOMLIST_SORT_MODE,
	LOBBY_BUTTON_ID_ROOMLIST_SORT_TITLE,
	LOBBY_BUTTON_ID_ROOMLIST_SORT_PLAYER_CNT,
	LOBBY_BUTTON_ID_ROOMLIST_SORT_TOTAL_MONEY,
	LOBBY_BUTTON_ID_ROOMLIST_SORT_JOINSTATE,
	LOBBY_BUTTON_ID_ROOMLIST_SORT_RULETYPE,


	//VIP 소팅버튼
	LOBBY_BUTTON_ID_ROOMLIST_VIP_SORT_ROOM_NO,
	LOBBY_BUTTON_ID_ROOMLIST_VIP_SORT_LIMIT,
	LOBBY_BUTTON_ID_ROOMLIST_VIP_SORT_SEED_BETRULE,
	LOBBY_BUTTON_ID_ROOMLIST_VIP_SORT_MODE,
	LOBBY_BUTTON_ID_ROOMLIST_VIP_SORT_TITLE,
	LOBBY_BUTTON_ID_ROOMLIST_VIP_SORT_PLAYER_CNT,
	LOBBY_BUTTON_ID_ROOMLIST_VIP_SORT_TOTAL_MONEY,
	LOBBY_BUTTON_ID_ROOMLIST_VIP_SORT_JOINSTATE,	

	

	LRO_WIDGET_ID_ROOMINFO_UNIT, 
	LRO_WIDGET_ID_ROOMINFO_UNIT_RESERVE= LRO_WIDGET_ID_ROOMINFO_UNIT+500,

	
	//룸정보다이얼로그	
	LOBBY_WIDGET_ID_ROOMINFO_DIALOG,
	LRI_BUTTON_ID_ROOMINFO_DIALOG_CLOSE,
	LRI_BUTTON_ID_ROOMINFO_DIALOG_JOINROOM,
	LRI_BUTTON_ID_ROOMINFO_DIALOG_OBSERVEROOM,


	LRI_WIDGET_ID_ROOMINFO_INFOTAB,
	LRI_WIDGET_ID_ROOMINFO_INFOTAB_STATE,
	LRI_BUTTON_ID_ROOMINFO_PLAYERINFO,
	LRI_BUTTON_ID_ROOMINFO_OBSERVERINFO,

	LRI_WIDGET_ID_ROOMINFO_PLAYERINFO_LIST,
	LRI_WIDGET_ID_ROOMINFO_OBSERVERINFO_LIST,

	LRI_WIDGET_ID_ROOMINFO_LIST_UPBUTTON,		//유저 리스트 (업버튼)
	LRI_WIDGET_ID_ROOMINFO_LIST_DOWNBUTTON,		//유저 리스트 (다운버튼)
	LRI_WIDGET_ID_ROOMINFO_LIST_THUMBBUTTON,	//유저 리스트 (썸버튼)

	LRI_WIDGET_ID_ROOMINFO_USERLIST_UNIT, 
	LRI_WIDGET_ID_ROOMINFO_USERLIST_UNIT_RESERVE= LRI_WIDGET_ID_ROOMINFO_USERLIST_UNIT+100,


	//보유머니에맞는게임방만보기
	LRI_BUTTON_ID_JOINABLE,
	LOBBY_BUTTON_ID_SHOW_PREV_JOINED_ROOM,


	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	//CHAT VIEW
	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	LOBBY_WIDGET_ID_CHATVIEW,
	LCV_EDIT_SENDCHAT,
	LCV_BUTTON_ID_OPENCHAT,
	LCV_BUTTON_ID_112,
	LCV_CHATVIEW_CHAT,
	LCV_BUTTON_ID_CHATSCROLL_UP,
	LCV_BUTTON_ID_CHATSCROLL_DOWN,
	LCV_BUTTON_ID_CHATSCROLL_THUMB,



	

	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	//MYINFO VIEW
	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	LOBBY_WIDGET_ID_MYINFO,
	LOBBY_WIDGET_ID_HIDESTATE,
	LOBBY_WIDGET_ID_DETAILINFO,
	LOBBY_WIDGET_ID_MYINFO_STATE,
	LMV_BUTTON_ID_FREECHARGE,
	LMV_BUTTON_ID_PULLDOWN,
	LMV_BUTTON_ID_PULLUP,

	LMV_BUTTON_ID_JOIN_INSURANCE,		// 보험 지급받기 버튼
	LMV_BUTTON_ID_JOIN_INSURANCE_GOLD,	// 골드 보험 지급받기 버튼 

	LMV_BUTTON_ID_FAMILY_ADVANTAGE,		// 패밀리 혜택받기 버튼



	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	//JACKPOT STATUS DISPLAY DIALOG
	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	LOBBY_WIDGET_ID_JACKPOT_DISPLAY_DIALOG,

	LOBBY_BUTTON_ID_JACKPOT_DISPLAY_DIALOG_CLOSE,		//닫기 버튼
	LOBBY_BUTTON_ID_JACKPOT_DISPLAY_DIALOG_DETAIL,		// 잭팟안내 및 당첨자 보기 버튼
	
	LOBBY_BUTTON_ID_JACKPOT_DISPLAY_DIALOG_TABBUTTON,	//탭버튼
	LOBBY_BUTTON_ID_JACKPOT_DISPLAY_DIALOG_TABBUTTON_BUFFER = LOBBY_BUTTON_ID_JACKPOT_DISPLAY_DIALOG_TABBUTTON+100,		//탭버튼버퍼
	


	LOBBY_WIDGET_ID_JACKPOT_DISPLAY_DIALOG_TAB, 
	LOBBY_WIDGET_ID_JACKPOT_DISPLAY_DIALOG_TAB_BUFFER = LOBBY_WIDGET_ID_JACKPOT_DISPLAY_DIALOG_TAB+100,
	LOBBY_WIDGET_ID_JACKPOT_DISPLAY_DIALOG_STATE,
	




	/////////////////////////////////////////////////////////////////////////////////////////////////////////
	///COMMAND ID
	/////////////////////////////////////////////////////////////////////////////////////////////////////////	
	ID_LOBBY_PROCESS,
	ID_LOBBY_PROCESS_ASKROOMINFO,
	ID_LOBBY_PROCESS_JOINROOM,	
	ID_LOBBY_PROCESS_AUTOJOIN,
	ID_LOBBY_PROCESS_TEST,
	ID_LOBBY_PROCESS_TEST2,
	ID_LOBBY_PROCESS_CREATEROOM,	
	ID_LOBBY_PROCESS_CHANGEGAME,
	ID_LOBBY_PROCESS_CHANGETOURNAMENTGAME,
	ID_LOBBY_PROCESS_PROFILE,
	ID_LOBBY_PROCESS_REFRESHCHANCEITEM,		//찬스아이템버튼을 리프레시 한다. 
	ID_LOBBY_PROCESS_RECHANLLENGE,			// 머니게이지 영역의 툴팁 재도전하기 클릭 (포커상점열기)
	ID_LOBBY_PROCESS_ASK_USERINFO,			// 서버에 유저정보를 요청한다 (wParam: SMALLUSERINFO구조체 포인터)
	ID_LOBBY_PROECSS_AVATAR_SHOP,			// 포커상점 창을 띄운다.(wParam: 탭번호, lParam: URL경로)
	ID_LOBBY_PROCESS_EVENTDLG_TABNO,		// 탭번호로 이벤트창을 띄운다. 
 	ID_LOBBY_PROCESS_REMOVE_SELECTED_ROOM,		// 선택방 정보를 지운다.

	
};
 


