// GameRes.cpp: implementation of the CGameRes class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "GameRes.h"

void RegistCommonSoundFiles()
{
	NMBASE::SOUND::g_Sound.RegistWav(SND_BUTTON_CLICK_A, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_BUTTON_CLICK_B, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_BUTTON_CLICK_C, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_BUTTON_CLICK_D, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_BUTTON_CLICK_E, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_WHISPER, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);		// 귓말 알림
	NMBASE::SOUND::g_Sound.RegistWav(SND_MEMORECEIVE, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);

	// 골드 출석부 관련 사운드
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_BUTTON, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_CARD_OPEN, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_CARD_WIN_1, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_CARD_WIN_2, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_CARD_WIN_3, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_CARD_WIN_4, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_CARD_SLIDE_1, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_CARD_SLIDE_2, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_HIDDEN_CARD, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_WIND_1, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_WIND_2, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);

	// 럭키 팡팡 관련 사운드
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_BJ_BEFORE_WIN, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_SPIN_MIX, NMBASE::SOUND::SNDPRIORITY_MID, FALSE);
	NMBASE::SOUND::g_Sound.RegistWav(SND_FX_BJ_WIN, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);

	NMBASE::SOUND::g_Sound.ClearGameLoadList();
}