#pragma once

#define	SND_PATH_M		".\\PokerCommon\\Sound\\M\\"
#define SND_PATH_F		".\\PokerCommon\\Sound\\F\\"
#define SND_PATH_EFFECT	".\\PokerCommon\\Sound\\effect\\"

#define SND_ALLIN	"allin.wav"
#define SND_ALLIN_H	"allin_hidden.wav"
#define SND_CALL	"call.wav"
#define SND_CALL_H	"call_hidden.wav"
#define SND_CHECK	"check.wav"
#define SND_CHECK_H	"check_hidden.wav"
#define SND_DDANG	"ddang.wav"
#define SND_DDANG_H	"ddang_hidden.wav"
#define SND_DIE		"die.wav"
#define SND_DIE_H	"die_hidden.wav"
#define SND_HALF	"half.wav"
#define SND_HALF_H	"half_hidden.wav"
#define SND_PING	"ping.wav"
#define SND_PING_H	"ping.wav"
#define SND_MAX		"max.wav"
#define SND_MAX_H	"max_hidden.wav"
#define SND_FULL	"full.wav"
#define SND_FULL_H	"full_hidden.wav"

#define SND_LOSE_ALLIN			"lose_allin.wav"
#define SND_LOSE_NORMAL			"lose_normal.wav"
#define SND_START				"start.wav"
#define SND_WIN_HIGH			"win_high.wav"
#define SND_WIN_LOW				"win_low.wav"
#define SND_CARD_SELECT			"cardselect.wav"
#define SND_CARD_MOVE			"cardmove.wav"
#define SND_CHIP				"chip.wav"
#define SND_MYTURN				"myturn.wav"
#define SND_JOKERSHOW			"jokershow.wav"
#define SND_JOKERCHANGE			"jokerchange.wav"
#define SND_BONUS_MOVE_CENTER	"bonusmovecenter.wav"
#define SND_HIDDEN_BGM			".\\PokerCommon\\Sound\\effect\\hiddenbgm.ogg"
#define SND_HIDDEN_OPEN			"hiddenopen.wav"
#define SND_TIMER				"Timeover.wav"
#define SND_HANDOEFT			"HandoEft.wav"
#define SND_VIPROOMJOIN			"vipjoin.wav"
#define SND_USERIN				"user_in.wav"
#define SND_USEROUT				"user_out.wav"
#define SND_MADE				"bd_made.wav"
#define SND_PROMOTION_SUMMER    "promotion_summer.wav"

#define SND_JP_END              "jp_end.wav"
#define SND_JP_FX               "jp_fx.wav"
//#define SND_JP_NOMI1            "jp_nomi1.wav"
//#define SND_JP_NOMI1_1          "jp_nomi1_1.wav"
#define SND_JP_NOMI1_2          "jp_nomi1_2.wav"
#define SND_JP_NOMI2            "jp_nomi2.wav"
#define SND_JP_NOTI             "jp_noti.wav"
#define SND_JP_PRIZE            "jp_prize.wav"
#define SND_JP_SELECT           "jp_select.wav"
#define SND_JP_START1_BGM       "jp_Start1_bgm.wav"
#define SND_JP_START1_FX        "jp_start1_fx.wav"
#define SND_JP_START2_BGM       "jp_start2_bgm.wav"
#define SND_JP_START2_FX        "jp_start2_fx.wav"
#define SND_JP_TIMER            "jp_timer.wav"
#define SND_JP_WIN_BGM          "jp_win_bgm.wav"
//#define SND_JP_WIN_FX           "jp_win_fx.wav"

#define SND_CUT_1	"bd_cut_1.wav"
#define SND_CUT_2	"bd_cut_2.wav"
#define SND_CUT_3	"bd_cut_3.wav"
#define SND_CUT_4	"bd_cut_4.wav"
#define SND_PASS	"bd_pass.wav"
#define SND_MON		"bd_mon.wav"
#define SND_AFT		"bd_aft.wav"
#define SND_NIG		"bd_nig.wav"

UPG_GAMEBASE_EXPORT extern void PBRegistSoundFiles();
UPG_GAMEBASE_EXPORT extern void PBPlaySound(bool bMan, LPCTSTR lpCommand);
UPG_GAMEBASE_EXPORT extern void PBPlayEffectSound(LPCTSTR lpCommand);
UPG_GAMEBASE_EXPORT extern void PBStopEffectSound(LPCTSTR lpCommand);
UPG_GAMEBASE_EXPORT extern BOOL PBAutoPlayMSceneSound(NMBASE::GRAPHICGDI::xSprite* pSpr, int mscn);
