// SOUNDRes.cpp: implementation of the CGameRes class.
//
//////////////////////////////////////////////////////////////////////

#include "stdafx.h"
#include "SoundRes.h"
#include "GlobalGame.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

void RegistSoundFiles()
{

	// 음악(OGG 파일)
	NMBASE::SOUND::g_Sound.RegistOggStream(MUSIC_OGG01, NMBASE::SOUND::SNDPRIORITY_MID, TRUE);		// OGG 음악 1
	NMBASE::SOUND::g_Sound.RegistOggStream(MUSIC_OGG02, NMBASE::SOUND::SNDPRIORITY_MID, TRUE);		// OGG 음악 2
	NMBASE::SOUND::g_Sound.RegistOggStream(MUSIC_OGG03, NMBASE::SOUND::SNDPRIORITY_MID, TRUE);		// OGG 음악 3	
	NMBASE::SOUND::g_Sound.RegistOggStream(MUSIC_OGG04, NMBASE::SOUND::SNDPRIORITY_MID, TRUE);		// OGG 음악 4
	NMBASE::SOUND::g_Sound.RegistOggStream(MUSIC_OGGTheme, NMBASE::SOUND::SNDPRIORITY_MID, TRUE);	// OGG 테마음악 3


	NMBASE::SOUND::g_Sound.RegistWav(SND01, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND02_1, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);//
	NMBASE::SOUND::g_Sound.RegistWav(SND02_2, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);//
	NMBASE::SOUND::g_Sound.RegistWav(SND03, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND04, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND05, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND06, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND07, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND08, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND09, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND10, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND11, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND12, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND13, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND14, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND18, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND19, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND20, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND21, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND22, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND23, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND24, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND25, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND26, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	
	NMBASE::SOUND::g_Sound.RegistWav(SND30, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND31, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND32, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND33, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND34, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND35, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND36, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND37, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND38, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND39, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND40, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND41, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND42, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND43, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	NMBASE::SOUND::g_Sound.RegistWav(SND44, NMBASE::SOUND::SNDPRIORITY_MID, 1, FALSE);	//
	
	
//############### 남성 ###############
	// ### [사운드 추가] ###
//############### 남성 ###############

//## 김두환 버전 ##//
//강제퇴장
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_1, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE, FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_2, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE, FALSE);	// 다이

//초구
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_3, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,  FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_4, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,  FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_5, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,  FALSE);	// 다이


//히든카드
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_6, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,  FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_7, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,  FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_8, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,  FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_9, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,  FALSE);	// 다이

//게임입장
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_10, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_11, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_12, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_13, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_14, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//관전 
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_15, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_16, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_17, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_18, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_19, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//족보
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_20, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_21, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_22, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_23, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_24, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_25, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_26, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_27, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_28, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_29, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//11
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_30, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_31, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_32, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_33, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_34, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_35, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_36, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_37, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_38, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_39, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//21

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_40, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_41, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_42, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_43, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_44, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_45, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_46, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_47, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_48, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_49, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//31
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_50, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_51, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_52, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_53, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_54, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_55, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_56, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_57, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_58, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_59, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//41
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_60, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_61, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_62, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_63, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_64, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_65, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_66, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_67, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_68, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_69, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//히든족보완성
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_70, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_71, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//히든족보실패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_72, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_73, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//상대올인시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_74, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_75, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_76, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_77, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//자신올인시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_78, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_79, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_80, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_81, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_82, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//배팅
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_83, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_84, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_85, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_86, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_87, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_88, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_89, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_90, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_91, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_92, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_93, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_94, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_95, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_96, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_97, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_98, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_99, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//한끗차이패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_100, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_101, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//드롭패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_102, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_103, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_104, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//일반패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_105, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_106, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_107, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_108, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//한끗차이승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_109, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_110, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//다이승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_111, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_112, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//대박승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_113, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_114, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_115, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_116, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//쪽박승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_117, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_118, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_119, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//일반승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_120, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_121, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_122, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//49다시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_123, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_124, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//동일족보비김
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_125, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//룸잭팟시작시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_126, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_127, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//룸잭팟승리시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_128, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM0_129, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이


//////////////////////////////////////////////////////////////////////////
//## 구마적 버전 ##//
//강제퇴장
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_1, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_2, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//초구
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_3, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_4, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_5, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이


//히든카드
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_6, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_7, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_8, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_9, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//게임입장
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_10, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_11, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_12, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_13, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_14, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//관전 
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_15, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_16, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_17, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_18, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_19, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//족보
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_20, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_21, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_22, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_23, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_24, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_25, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_26, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_27, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_28, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_29, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//11
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_30, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_31, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_32, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_33, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_34, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_35, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_36, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_37, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_38, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_39, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//21

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_40, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_41, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_42, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_43, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_44, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_45, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_46, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_47, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_48, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_49, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//31
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_50, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_51, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_52, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_53, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_54, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_55, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_56, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_57, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_58, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_59, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//41
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_60, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_61, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_62, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_63, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_64, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_65, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_66, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_67, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_68, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_69, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//히든족보완성
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_70, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_71, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//히든족보실패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_72, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_73, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//상대올인시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_74, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_75, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_76, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_77, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//자신올인시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_78, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_79, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_80, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_81, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_82, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//배팅
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_83, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_84, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_85, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_86, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_87, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_88, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_89, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_90, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_91, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_92, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_93, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_94, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_95, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_96, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_97, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_98, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_99, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//한끗차이패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_100, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_101, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//드롭패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_102, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_103, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_104, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//일반패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_105, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_106, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_107, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_108, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//한끗차이승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_109, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_110, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//다이승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_111, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_112, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//대박승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_113, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_114, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_115, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_116, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//쪽박승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_117, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_118, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_119, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//일반승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_120, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_121, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_122, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//49다시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_123, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_124, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//동일족보비김
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_125, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//룸잭팟시작시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_126, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_127, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//룸잭팟승리시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_128, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDM1_129, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이



//############### 여성 ###############

//## 설향 버전 ##//
//강제퇴장
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_1, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_2, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//초구
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_3, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_4, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_5, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이


//히든카드
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_6, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_7, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_8, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_9, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//게임입장
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_10, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_11, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_12, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_13, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_14, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//관전 
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_15, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_16, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_17, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_18, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_19, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//족보
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_20, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_21, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_22, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_23, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_24, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_25, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_26, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_27, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_28, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_29, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//11
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_30, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_31, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_32, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_33, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_34, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_35, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_36, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_37, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_38, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_39, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//21

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_40, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_41, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_42, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_43, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_44, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_45, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_46, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_47, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_48, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_49, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//31
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_50, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_51, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_52, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_53, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_54, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_55, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_56, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_57, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_58, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_59, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//41
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_60, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_61, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_62, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_63, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_64, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_65, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_66, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_67, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_68, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_69, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//히든족보완성
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_70, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_71, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//히든족보실패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_72, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_73, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//상대올인시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_74, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_75, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_76, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_77, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//자신올인시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_78, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_79, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_80, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_81, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_82, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//배팅
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_83, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_84, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_85, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_86, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_87, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_88, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_89, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_90, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_91, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_92, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_93, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_94, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_95, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_96, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_97, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_98, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_99, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//한끗차이패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_100, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_101, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//드롭패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_102, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_103, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_104, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//일반패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_105, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_106, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_107, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_108, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//한끗차이승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_109, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_110, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//다이승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_111, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_112, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//대박승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_113, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_114, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_115, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_116, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//쪽박승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_117, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_118, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_119, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//일반승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_120, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_121, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_122, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//49다시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_123, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_124, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//동일족보비김
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_125, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//룸잭팟시작시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_126, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_127, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//룸잭팟승리시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_128, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF0_129, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이


//////////////////////////////////////////////////////////////////////////
//## 애란 버전 ##//
//강제퇴장
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_1, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_2, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//초구
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_3, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_4, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
	NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_5, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이


//히든카드
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_6, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_7, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_8, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_9, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//게임입장
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_10, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_11, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_12, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_13, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_14, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//관전 
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_15, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_16, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_17, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_18, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_19, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//족보
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_20, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_21, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_22, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_23, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_24, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_25, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_26, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_27, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_28, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_29, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//11
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_30, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_31, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_32, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_33, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_34, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_35, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_36, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_37, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_38, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_39, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//21

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_40, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_41, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_42, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_43, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_44, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_45, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_46, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_47, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_48, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_49, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//31
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_50, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_51, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_52, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_53, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_54, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_55, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_56, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_57, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_58, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_59, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//41
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_60, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_61, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_62, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_63, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_64, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_65, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_66, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_67, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_68, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_69, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//히든족보완성
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_70, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_71, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//히든족보실패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_72, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_73, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//상대올인시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_74, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_75, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_76, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_77, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//자신올인시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_78, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_79, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_80, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_81, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_82, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//배팅
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_83, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_84, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_85, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_86, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_87, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_88, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_89, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_90, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_91, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_92, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_93, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_94, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_95, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_96, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_97, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_98, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_99, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//한끗차이패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_100, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_101, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//드롭패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_102, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_103, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_104, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//일반패
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_105, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_106, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_107, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_108, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//한끗차이승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_109, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_110, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//다이승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_111, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_112, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//대박승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_113, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_114, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_115, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_116, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//쪽박승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_117, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_118, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_119, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//일반승
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_120, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_121, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_122, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//49다시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_123, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_124, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//동일족보비김
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_125, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//룸잭팟시작시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_126, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_127, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

//룸잭팟승리시
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_128, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이
		NMBASE::SOUND::g_Sound.RegistOggStream(SNDF1_129, NMBASE::SOUND::SNDPRIORITY_KEEPALIVE,FALSE);	// 다이

}