
#ifndef __BASE_CONNECTOR_API_ERRORNO_H__
#define __BASE_CONNECTOR_API_ERRORNO_H__

#define BASE_SUCCESS		0x00000000
#define BASE_ERROR_FLAG		0x00040100

#define BASE_ERROR_SYSTEM				(BASE_ERROR_FLAG | 0x0001)
#define BASE_ERROR_UNKNOWN				(BASE_ERROR_FLAG | 0x0002)
#define BASE_ERROR_CONFIG				(BASE_ERROR_FLAG | 0x0003)
#define BASE_ERROR_INVALID_PARAM		(BASE_ERROR_FLAG | 0x0004)
#define BASE_ERROR_TIMEOUT				(BASE_ERROR_FLAG | 0x0005)
#define BASE_ERROR_NOT_EXIST			(BASE_ERROR_FLAG | 0x0006)
#define BASE_ERROR_DUPLICATE			(BASE_ERROR_FLAG | 0x0007)
#define BASE_ERROR_NOT_ENOUGH_MEMORY	(BASE_ERROR_FLAG | 0x0008)
#define BASE_ERROR_NOT_SUPPORT			(BASE_ERROR_FLAG | 0x0009)
#define BASE_ERROR_NOT_INIT			(BASE_ERROR_FLAG | 0x000A)
#define BASE_ERROR_INVALID_VALUE		(BASE_ERROR_FLAG | 0x000B)
#define BASE_ERROR_INVALID_TYPE		(BASE_ERROR_FLAG | 0x000C)
#define BASE_ERROR_COLLISION_KEY		(BASE_ERROR_FLAG | 0x000D)
#define BASE_ERROR_NOT_EXIST_KEY		(BASE_ERROR_FLAG | 0x000F)
#define BASE_ERROR_SOCKET_ERROR		(BASE_ERROR_FLAG | 0x0010)
#define BASE_ERROR_SOCKET_BINDING		(BASE_ERROR_FLAG | 0x0011)
#define BASE_ERROR_SOCKET_CLOSED		(BASE_ERROR_FLAG | 0x0012)
#define BASE_ERROR_CONNECT				(BASE_ERROR_FLAG | 0x0013)
#define BASE_ERROR_CLOSED				(BASE_ERROR_SOCKET_CLOSED)
#define BASE_ERROR_ALREADY_BIND		(BASE_ERROR_SOCKET_BINDING)
#define BASE_ERROR_INVALID_STATE		(BASE_ERROR_FLAG | 0x0014)



#endif	// #ifndef __BASE_CONNECTOR_API_BASE_H__
