#pragma once

//UPG작업 BaseObject에있던 enum ENUM_ANIFILEID을 여기로 옮김
// 오브젝트 종류

enum ENUM_ANIFILEID
{
	/////////////////////////////	
	ANF_NONE = -1,	
		
	ANF_BET_CMD = 10,			// 배팅 Animation
	ANF_BET_HALF,
	ANF_BET_CALL,
	ANF_BET_CHECK,
	ANF_BET_DADANG,
	ANF_BET_PING,
	ANF_BET_DIE,
	ANF_BET_ALLIN,
	
	ANF_BET_RAISE_X1,
	ANF_BET_RAISE_X2,
	ANF_BET_RAISE_X3,

	ANF_PLAYER_WINEFFECT,		// 승리 효과
	ANF_PLAYER_ALLINMARK,		// 올인 마크
	ANF_PLAYER_JEKICHARGE,		// 재기충전
	ANF_PLAYER_CUTINGSELECT,	// 커팅 선택중 이미지.	
	ANF_PLAYER_CUTINGSELECTED,	// 커팅 선택 완료
	ANF_PLAYER_CUTTINGNUMBER,	// 커팅 횟수 ,패스		
	ANF_PLAYER_TIMEBAR,			// 타임바
	ANF_PLAYER_JOKBOEFFECT,		// 족보 이펙트
	ANF_PLAYER_CHANCEITEM,		// 찬스아이템	
	ANF_PLAYER_OBSERVER,		// 관전자 이미지
	
	ANF_SDLG_GRADE,
	ANF_CUTINFO_BD,	
	ANF_HANDO,					//보유한도.
	ANF_PLAYER_COMPLETEMADE_EFT,	// 메이드이펙트
	ANF_BET_FULL,
};
